# 以下是ppyoloe_crn_l_80e_sliced_eda.yml的内容

_BASE_: [
  './_base_/eda_sliced_640_025_detection.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/ppyoloe_crn.yml',
  './_base_/ppyoloe_reader.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/ppyoloe_crn_l_80e_sliced_visdrone_640_025/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyoloe_crn_l_300e_coco.pdparams
depth_mult: 1.0
width_mult: 1.0


TrainReader:
  batch_size: 8

EvalReader:
  batch_size: 1

TestReader:
  batch_size: 1
  fuse_normalize: True


epoch: 80
LearningRate:
  base_lr: 0.001
  schedulers:
    - !CosineDecay
      max_epochs: 96
    - !LinearWarmup
      start_factor: 0.
      epochs: 1

PPYOLOEHead:
  static_assigner_epoch: -1
  nms:
    name: MultiClassNMS
    nms_top_k: 10000
    keep_top_k: 500
    score_threshold: 0.01
    nms_threshold: 0.6


# EvalDataset:
#   !COCODataSet
#     image_dir: val_images_640_025
#     anno_path: val_640_025.json
#     dataset_dir: dataset/visdrone_sliced

# EvalDataset:
#   !COCODataSet
#     image_dir: VisDrone2019-DET-val
#     anno_path: val.json
#     dataset_dir: dataset/visdrone

# 以下是eda_sliced_640_025_detection.yml的内容
metric: COCO
num_classes: 4

TrainDataset:
  !COCODataSet
    image_dir: /home/aistudio/PaddleDetection/dataset/voc/IMG_sliced/train_images_640_025
    anno_path: /home/aistudio/PaddleDetection/dataset/voc/IMG_sliced/train_640_025.json
    dataset_dir: /home/aistudio/PaddleDetection/dataset/voc
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: /home/aistudio/PaddleDetection/dataset/voc/IMG_sliced/val_images_640_025
    anno_path: /home/aistudio/PaddleDetection/dataset/voc/IMG_sliced/val_640_025.json
    dataset_dir: /home/aistudio/PaddleDetection/dataset/voc

TestDataset:
  !ImageFolder
    anno_path: val_640_025.json
    dataset_dir: /home/aistudio/PaddleDetection/dataset/voc/IMG_sliced


# 以下是runtime.yml的内容
use_gpu: true
use_xpu: false
use_mlu: false
use_npu: false
log_iter: 20
save_dir: output
snapshot_epoch: 1
print_flops: false
print_params: false

# Exporting the model
export:
  post_process: True  # Whether post-processing is included in the network when export model.
  nms: True           # Whether NMS is included in the network when export model.
  benchmark: False    # It is used to testing model performance, if set `True`, post-process and NMS will not be exported.
  fuse_conv_bn: False


# 以下是optimizer_300e.yml的内容
epoch: 300

LearningRate:
  base_lr: 0.01
  schedulers:
    - name: CosineDecay
      max_epochs: 360
    - name: LinearWarmup
      start_factor: 0.
      epochs: 5

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2


# 以下是ppyoloe_crn.yml的内容
architecture: YOLOv3
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998
ema_black_list: ['proj_conv.weight']
custom_black_list: ['reduce_mean']

YOLOv3:
  backbone: CSPResNet
  neck: CustomCSPPAN
  yolo_head: PPYOLOEHead
  post_process: ~

CSPResNet:
  layers: [3, 6, 6, 3]
  channels: [64, 128, 256, 512, 1024]
  return_idx: [1, 2, 3]
  use_large_stem: True

CustomCSPPAN:
  out_channels: [768, 384, 192]
  stage_num: 1
  block_num: 3
  act: 'swish'
  spp: true

PPYOLOEHead:
  fpn_strides: [32, 16, 8]
  grid_cell_scale: 5.0
  grid_cell_offset: 0.5
  static_assigner_epoch: 100
  use_varifocal_loss: True
  loss_weight: {class: 1.0, iou: 2.5, dfl: 0.5}
  static_assigner:
    name: ATSSAssigner
    topk: 9
  assigner:
    name: TaskAlignedAssigner
    topk: 13
    alpha: 1.0
    beta: 6.0
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 300
    score_threshold: 0.01
    nms_threshold: 0.7


# 以下是ppyoloe_reader.yml的内容
worker_num: 4
eval_height: &eval_height 640
eval_width: &eval_width 640
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - PadGT: {}
  batch_size: 8
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 2

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1


