_BASE_: [
  '_base_/yidaiyilu.yml',
  '_base_/runtime.yml',
]

snapshot_epoch: 2

architecture: YOLOv3
pretrain_weights: https://paddledet.bj.bcebos.com/models/ppyolov2_r50vd_dcn_365e_coco.pdparams
weights: output/ppyolov2_r50vd_dcn_optimize/best_model.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  neck: PPYOLOREDUCEPAN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

ResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  dcn_v2_stages: [3]
  freeze_at: 1
  freeze_norm: false
  norm_decay: 0.

PPYOLOREDUCEPAN:
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true

YOLOv3Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss
  iou_aware: true
  iou_aware_factor: 0.5

YOLOv3Loss:
  ignore_thresh: 0.55
  downsample: [32, 16, 8]
  label_smooth: false
  scale_x_y: 1.05
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss

IouLoss:
  loss_weight: 2.5
  loss_square: true

IouAwareLoss:
  loss_weight: 1.0

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.01
    downsample_ratio: 32
    clip_bbox: true
    scale_x_y: 1.05

  nms:
    name: MultiClassNMS
    keep_top_k: 1000
    score_threshold: 0.01
    nms_threshold: 0.999
    nms_top_k: 1000


worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {hue: [-6, 6, 0.5], saturation: [0.8, 1.2, 0.5], contrast: [0.7, 1.3, 0.5], brightness: [0.6, 1.3, 0.5]}
      #- GridMask: {prob: 0.5}
    - RandomExpand: {ratio: 1.5, fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {aspect_ratio: [0.8, 1.3], scaling: [0.7, 1.0], thresholds: [.5, .7, .9]}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [384, 416, 448, 480, 512, 544], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 8
  shuffle: true
  drop_last: true
  mixup_epoch: 72
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [480, 480], keep_ratio: False, interp: 1}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 4

TestReader:
  inputs_def:
    image_shape: [3, 480, 480]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [480, 480], keep_ratio: False, interp: 1}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1


epoch: 40

LearningRate:
  base_lr: 0.003
  schedulers:
  - !PiecewiseDecay
    gamma: 0.2
    milestones:
    - 36
  - !LinearWarmup
    start_factor: 0.
    steps: 100

OptimizerBuilder:
  clip_grad_by_norm: 35.
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
    
# base_yidaiyilu.yml
metric: COCO
num_classes: 7

TrainDataset:
  !COCODataSet
    image_dir: JPEGImages
    anno_path: train_final.json
    dataset_dir: /home/aistudio/data/data97737/detection/
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: JPEGImages
    anno_path: val_final.json
    dataset_dir: /home/aistudio/data/data97737/detection/

TestDataset:
  !ImageFolder
    anno_path: val_final.json


# '_base_/runtime.yml',
use_gpu: true
log_iter: 50
save_dir: output
snapshot_epoch: 1
